import type { NetworkConfig, NetworkId } from '../types/wallet';

export const NETWORKS: Record<NetworkId, NetworkConfig> = {
  ethereum: {
    id: 'ethereum',
    name: 'Ethereum Mainnet',
    shortName: 'Ethereum',
    chainId: 1,
    rpcUrl: 'https://eth.llamarpc.com',
    symbol: 'ETH',
    decimals: 18,
    explorerUrl: 'https://etherscan.io',
    color: '#627EEA',
  },
  sepolia: {
    id: 'sepolia',
    name: 'Sepolia',
    shortName: 'Sepolia',
    chainId: 11155111,
    rpcUrl: 'https://rpc.sepolia.org',
    symbol: 'ETH',
    decimals: 18,
    explorerUrl: 'https://sepolia.etherscan.io',
    color: '#CFB5F0',
    isTestnet: true,
  },
  polygon: {
    id: 'polygon',
    name: 'Polygon Mainnet',
    shortName: 'Polygon',
    chainId: 137,
    rpcUrl: 'https://polygon-rpc.com',
    symbol: 'POL',
    decimals: 18,
    explorerUrl: 'https://polygonscan.com',
    color: '#8247E5',
  },
  arbitrum: {
    id: 'arbitrum',
    name: 'Arbitrum One',
    shortName: 'Arbitrum',
    chainId: 42161,
    rpcUrl: 'https://arb1.arbitrum.io/rpc',
    symbol: 'ETH',
    decimals: 18,
    explorerUrl: 'https://arbiscan.io',
    color: '#28A0F0',
  },
  optimism: {
    id: 'optimism',
    name: 'OP Mainnet',
    shortName: 'Optimism',
    chainId: 10,
    rpcUrl: 'https://mainnet.optimism.io',
    symbol: 'ETH',
    decimals: 18,
    explorerUrl: 'https://optimistic.etherscan.io',
    color: '#FF0420',
  },
  base: {
    id: 'base',
    name: 'Base',
    shortName: 'Base',
    chainId: 8453,
    rpcUrl: 'https://mainnet.base.org',
    symbol: 'ETH',
    decimals: 18,
    explorerUrl: 'https://basescan.org',
    color: '#0052FF',
  },
  bsc: {
    id: 'bsc',
    name: 'BNB Smart Chain',
    shortName: 'BSC',
    chainId: 56,
    rpcUrl: 'https://bsc-dataseed.binance.org',
    symbol: 'BNB',
    decimals: 18,
    explorerUrl: 'https://bscscan.com',
    color: '#F0B90B',
  },
  localhost: {
    id: 'localhost',
    name: 'Localhost 8545',
    shortName: 'Localhost',
    chainId: 1337,
    rpcUrl: 'http://127.0.0.1:8545',
    symbol: 'ETH',
    decimals: 18,
    explorerUrl: '',
    color: '#BBC0C5',
    isTestnet: true,
  },
};

export const DEFAULT_NETWORK: NetworkId = 'ethereum';

export function getNetworkByChainId(chainId: number): NetworkConfig | undefined {
  return Object.values(NETWORKS).find((n) => n.chainId === chainId);
}
